/**
 * Amplify bootstrap.
 *
 * `amplify_outputs.json` is generated by Amplify — by `npx ampx sandbox`
 * locally, and by `npx ampx pipeline-deploy` during the Amplify Hosting build.
 * It is gitignored, so it is absent on a fresh clone.
 *
 * We therefore load it with `import.meta.glob`, which resolves to an empty
 * object when the file does not exist instead of failing the Vite build the way
 * a static `import outputs from '../amplify_outputs.json'` would. No outputs
 * file → the whole app falls back to durable on-device storage and still works.
 *
 * Nothing here uses top-level await: `ready` is a promise every exported call
 * awaits internally, so React can render immediately and the first data read
 * simply queues behind initialisation.
 */

import { readLibraryMode, SHARED_OWNER_KEY } from './libraryMode.js';

const outputsModules = import.meta.glob('/amplify_outputs*.json', { eager: true });
const outputsEntry = Object.values(outputsModules)[0];
const outputs = outputsEntry?.default ?? outputsEntry ?? null;

/**
 * Private or shared, decided at build time from VITE_SHARED_LIBRARY.
 *
 * Read once here rather than at every call site, so there is exactly one place
 * that decides and one thing to check when asking "is this deployment shared?".
 */
const libraryMode = readLibraryMode(import.meta.env || {});

/** True when this build serves one library to everyone who opens the URL. */
export function isSharedLibrary() {
  return libraryMode.shared;
}

/** For the UI to report a misconfigured value rather than silently ignoring it. */
export function libraryModeSetting() {
  return { ...libraryMode };
}

/** Set once initialisation settles. Read it through `whenReady()`. */
let configured = false;
let dataClient = null;
let signedIn = false;

async function init() {
  if (!outputs || !outputs.auth) return false;
  try {
    const { Amplify } = await import('aws-amplify');
    Amplify.configure(outputs);
    configured = true;
  } catch (err) {
    console.warn(
      '[serotonin] amplify_outputs.json is present but Amplify could not be configured — using on-device storage instead.',
      err,
    );
    configured = false;
  }
  return configured;
}

let ready = init();

/** Resolves to true when a real AWS backend is behind this build. */
export function whenReady() {
  return ready;
}

/**
 * Synchronous view of the same flag, for render-time labels. False until
 * initialisation settles, which takes one microtask when outputs are absent.
 */
export function isAmplifyConfigured() {
  return configured;
}

/** Lazily create (and memoise) the generated Amplify Data client. */
export async function getDataClient() {
  if (!(await ready)) return null;
  if (!dataClient) {
    try {
      const { generateClient } = await import('aws-amplify/data');
      dataClient = generateClient({ authMode: 'identityPool' });
    } catch (err) {
      console.warn('[serotonin] Could not create the Amplify Data client.', err);
      return null;
    }
  }
  return dataClient;
}

let ownerKeyPromise = null;

/**
 * Stable per-caller key used to scope every record.
 *
 * Signed in  → the Cognito user ID (`sub`), which survives everything.
 * Guest      → the Cognito identity ID, cached in local storage by the Amplify
 *              SDK. Clearing site data orphans the old records; that is the cost
 *              of deferring auth, and it is called out in AMPLIFY_SETUP.md.
 * No backend → a random ID we mint and keep in local storage ourselves.
 */
export async function getOwnerKey() {
  if (!ownerKeyPromise) {
    ownerKeyPromise = resolveOwnerKey().catch((err) => {
      console.warn('[serotonin] Falling back to a local owner key.', err);
      return localOwnerKey();
    });
  }
  return ownerKeyPromise;
}

async function resolveOwnerKey() {
  // Shared mode short-circuits identity entirely: one key, everyone. Applied
  // before the backend check so the device-only path behaves the same way —
  // otherwise turning the flag on would appear to work locally and change
  // nothing once deployed, or the reverse.
  if (libraryMode.shared) {
    // `signedIn` still needs resolving, because the S3 prefix depends on it.
    if (await ready) {
      try {
        const { fetchAuthSession } = await import('aws-amplify/auth');
        const session = await fetchAuthSession();
        signedIn = !!session?.tokens?.idToken;
      } catch { /* guest; the default is already false */ }
    }
    return SHARED_OWNER_KEY;
  }

  if (!(await ready)) return localOwnerKey();
  const { fetchAuthSession } = await import('aws-amplify/auth');
  const session = await fetchAuthSession();
  const sub = session?.tokens?.idToken?.payload?.sub;
  signedIn = !!session?.tokens?.idToken;
  if (sub) return String(sub);
  if (session?.identityId) return String(session.identityId);
  return localOwnerKey();
}

/** True when a Cognito user (not a guest) is signed in. Resolve `getOwnerKey` first. */
export function isSignedIn() {
  return signedIn;
}

let identityPromise = null;

/**
 * The Cognito *identity* ID, which is what S3 path rules match on via the
 * `{entity_id}` token. Distinct from `getOwnerKey()`: a signed-in user is scoped
 * by their user ID for records, but by their identity ID for objects.
 *
 * Returns null with no backend configured, which is the signal to store the
 * bytes on-device instead.
 */
export async function getIdentityId() {
  if (!identityPromise) {
    identityPromise = (async () => {
      if (!(await ready)) return null;
      const { fetchAuthSession } = await import('aws-amplify/auth');
      const session = await fetchAuthSession();
      return session?.identityId ? String(session.identityId) : null;
    })().catch((err) => {
      console.warn('[serotonin] Could not resolve the Cognito identity ID.', err);
      return null;
    });
  }
  return identityPromise;
}

const LOCAL_OWNER_STORAGE_KEY = 'serotonin.ownerKey';

function localOwnerKey() {
  try {
    const existing = localStorage.getItem(LOCAL_OWNER_STORAGE_KEY);
    if (existing) return existing;
    const minted = `local-${Math.random().toString(36).slice(2)}${Date.now().toString(36)}`;
    localStorage.setItem(LOCAL_OWNER_STORAGE_KEY, minted);
    return minted;
  } catch {
    return 'local-anonymous';
  }
}

/**
 * Drop memoised identity state. Call after sign-in or sign-out so record
 * scoping and the S3 prefix re-resolve against the new caller.
 */
export function resetIdentityCache() {
  ownerKeyPromise = null;
  identityPromise = null;
  signedIn = false;
}
